# Interactive component

The aim of this section is to show to the readers that how one data file can be used to draw plots in 
different point of views, and how information shown from one plot could be limited. The above two plot 
tells different information about one data set. Each one of them has some limitations of showing some 
aspects of the data. However, if we considering the two plots together, We can understand this data 
more comprehensively.


## Description of the first interactive plot
The first interactive plot is a graph with multiple lines, where each line represents a State of 
the United States. Each State has been assigned with a color so it is easier for the reader to recognize
each State. Colors are randomlly assigned because similar colors represent connections in some way, and 
it is not reasonable to assume that there are relationships among each State regarding to the total revenue 
gained. It is easier for the readers to compare the trend of the total revenue gained among different States, 
or to find the trend of changing in total revenue among years of one State.The advantage of this graph is 
that it can show the total revenue trend very clearly! However, the disadvantage is that is it difficult to 
compare which parts of the United States tend to receive more revenue on selling milk or milk product. That 
means, the distribution of the total revenue of States cannot be shown on this graph.



<iframe src="milklines.html" width="700" height="700"></iframe>


* Instructions for using the plot
1. Clicking on the State names on the right, and the corresponding line can be added or deleted in the plot.
2. Each color represents one State, so the readers will not get confused about which line match to which State.
3. The units of the Y-axis is dollars per hundred pounds of milk sold





## Description of the second interactive plot
Compare to the previous plot, this interactive map plot is good at showing the distribution of the total revunue
on a map of the United States, however, it is difficult to tell from this interactive plot about the change of 
the total revenue of each States among the years since the "diiference in degree of blue" is not as clear as numbers.

<iframe src="revenueMap.html" width="700" height="700"></iframe>


* Instructions for using the map
1. Moving the mouse on the State to see the State's name and the total revenue in dollars 
per hundred pounds of weight sold.
2. Select the year on the upper left to see the total revenue map of year 2016-2020.


* references:
These are the usefu examples of D3 graphs that help us learn how to draw the graph above.

1. https://bl.ocks.org/dnprock/5215cc464cfb9affd283

2. https://bl.ocks.org/mbostock/4060606

3. https://bl.ocks.org/adamjanes/6cf85a4fd79e122695ebde7d41fe327f

4. https://bl.ocks.org/denisemauldin/3436a3ae06f73a492228059a515821fe

5. https://gist.github.com/lbui30/65c2707e615841efaf35959aedac8ca9


